// <auto-generated />
using System;
using Capet_OPS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Capet_OPS.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260218085759_AddJoinedRollCount")]
    partial class AddJoinedRollCount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Capet_OPS.Models.Entities.CanvasType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CnvDesc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cnv_desc");

                    b.Property<string>("CnvId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cnv_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("ErpCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("erp_code");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<decimal>("RollWidth")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("roll_width");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("ErpCode")
                        .IsUnique();

                    b.ToTable("fabric_types", (string)null);
                });

            modelBuilder.Entity("Capet_OPS.Models.Entities.FabricPiece", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AsPlan")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("as_plan");

                    b.Property<string>("BarcodeNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("barcode_no");

                    b.Property<string>("CnvDesc")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cnv_desc");

                    b.Property<string>("CnvId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cnv_id");

                    b.Property<string>("ItemNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("item_no");

                    b.Property<decimal>("Length")
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("length");

                    b.Property<string>("ListNo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("list_no");

                    b.Property<string>("OrderType")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("order_type");

                    b.Property<string>("Orno")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("orno");

                    b.Property<int?>("Qty")
                        .HasColumnType("integer")
                        .HasColumnName("qty");

                    b.Property<decimal?>("Sqm")
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("sqm");

                    b.Property<DateTime>("SyncedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal>("Width")
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.HasIndex("BarcodeNo")
                        .IsUnique();

                    b.HasIndex("CnvId");

                    b.HasIndex("Orno");

                    b.ToTable("fabric_pieces", (string)null);
                });

            modelBuilder.Entity("Capet_OPS.Models.Entities.LayoutPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CanvasTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("fabric_type_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal>("EfficiencyPct")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("efficiency_pct");

                    b.Property<int>("JoinedRollCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("joined_roll_count");

                    b.Property<string>("LayoutJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("layout_json");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("PieceCount")
                        .HasColumnType("integer")
                        .HasColumnName("piece_count");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("plan_code");

                    b.Property<decimal>("RollWidth")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("roll_width");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("planned")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalArea")
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("total_area");

                    b.Property<decimal>("TotalLength")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_length");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal>("UsedArea")
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("used_area");

                    b.Property<decimal>("WasteArea")
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("waste_area");

                    b.HasKey("Id");

                    b.HasIndex("CanvasTypeId");

                    b.HasIndex("PlanCode")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("layout_plans", (string)null);
                });

            modelBuilder.Entity("Capet_OPS.Models.Entities.LayoutPlanItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Area")
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("area");

                    b.Property<string>("AsPlan")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("as_plan");

                    b.Property<string>("BarcodeNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("barcode_no");

                    b.Property<string>("CnvDesc")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cnv_desc");

                    b.Property<string>("CnvId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cnv_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsRotated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_rotated");

                    b.Property<string>("ItemNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("item_no");

                    b.Property<int>("LayoutPlanId")
                        .HasColumnType("integer")
                        .HasColumnName("layout_plan_id");

                    b.Property<decimal>("Length")
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("length");

                    b.Property<string>("ListNo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("list_no");

                    b.Property<string>("OrderType")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("order_type");

                    b.Property<string>("Orno")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("orno");

                    b.Property<decimal>("PackLength")
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("pack_length");

                    b.Property<decimal>("PackWidth")
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("pack_width");

                    b.Property<decimal>("PackX")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,4)")
                        .HasDefaultValue(0m)
                        .HasColumnName("pack_x");

                    b.Property<decimal>("PackY")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,4)")
                        .HasDefaultValue(0m)
                        .HasColumnName("pack_y");

                    b.Property<int>("Qty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("qty");

                    b.Property<decimal?>("TagLength")
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("tag_length");

                    b.Property<decimal?>("TagWidth")
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("tag_width");

                    b.Property<decimal>("Width")
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.HasIndex("BarcodeNo");

                    b.HasIndex("LayoutPlanId");

                    b.ToTable("layout_plan_items", (string)null);
                });

            modelBuilder.Entity("Capet_OPS.Models.Entities.PlannedBarcode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BarcodeNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("barcode_no");

                    b.Property<int>("LayoutPlanId")
                        .HasColumnType("integer")
                        .HasColumnName("layout_plan_id");

                    b.Property<DateTime>("PlannedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("planned_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("BarcodeNo")
                        .IsUnique();

                    b.HasIndex("LayoutPlanId");

                    b.ToTable("planned_barcodes", (string)null);
                });

            modelBuilder.Entity("Capet_OPS.Models.Entities.LayoutPlan", b =>
                {
                    b.HasOne("Capet_OPS.Models.Entities.CanvasType", "CanvasType")
                        .WithMany()
                        .HasForeignKey("CanvasTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CanvasType");
                });

            modelBuilder.Entity("Capet_OPS.Models.Entities.LayoutPlanItem", b =>
                {
                    b.HasOne("Capet_OPS.Models.Entities.LayoutPlan", "LayoutPlan")
                        .WithMany("Items")
                        .HasForeignKey("LayoutPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LayoutPlan");
                });

            modelBuilder.Entity("Capet_OPS.Models.Entities.PlannedBarcode", b =>
                {
                    b.HasOne("Capet_OPS.Models.Entities.LayoutPlan", "LayoutPlan")
                        .WithMany("PlannedBarcodes")
                        .HasForeignKey("LayoutPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LayoutPlan");
                });

            modelBuilder.Entity("Capet_OPS.Models.Entities.LayoutPlan", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("PlannedBarcodes");
                });
#pragma warning restore 612, 618
        }
    }
}
